#!/bin/bash

today=$(date +"%Y-%m-%d")
if [[ $1 = "--new-instance" ]] 
then
emacs -batch -l ~/.config/doom/init.el -eval "(org-batch-store-agenda-views\
           org-agenda-span (quote day)\
           org-agenda-start-day \'$today\')" --kill > /dev/null
else
emacsclient -eval "(org-batch-store-agenda-views\
    org-agenda-span (quote day)\
    org-agenda-start-day \'$today\')" > /dev/null
fi
cat ~/Sync/org/agenda
